### ISSUE TITLE
problem with demjson importing

### ISSUE THREAD

**Issue by rezmal** [hongtaocai/googlefinance#19]
Hi
I keep getting this error when I want to use the package test run:

> > > from googlefinance import getQuotes
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "googlefinance/**init**.py", line 3, in <module>
> > >     import demjson
> > > ImportError: No module named demjson

Any idea how to fix this?

**Comment by jdeer0618** [comment]
`python -m pip install demjson` worked for me.

**Comment by cpatte7372** [comment]
Worked for me too.

Can close this case
Thanks

**Comment by matanzit** [comment]
getting an error when running example.py

raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden

**Comment by Bhanu-PP** [comment]
me too, getting
 print (json.dumps(getQuotes('AAPL'), indent=2))
 urllib.error.HTTPError: HTTP Error 403: Forbidden.
