### ISSUE TITLE
EndPoint in your example GetQuotes not working.

### ISSUE THREAD

**Issue by hgarcia101685** [hongtaocai/googlefinance#48]
I get a 403 error when trying to run your example:

`print(json.dumps(getQuotes('F'), indent=2))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\meraz\AppData\Local\Programs\Python\Python36\lib\site-packages\googlefinance\__init__.py", line 70, in getQuotes
    content = json.loads(request(symbols))
  File "C:\Users\meraz\AppData\Local\Programs\Python\Python36\lib\site-packages\googlefinance\__init__.py", line 33, in request
    resp = urlopen(req)
  File "C:\Users\meraz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\meraz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Users\meraz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\meraz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Users\meraz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\meraz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden`

**Comment by hongtaocai** [comment]
See readme

**Comment by roshanreji92** [comment]
I am not certain as to what in the readme I am missing. I am facing the same error.

**Comment by addisonlynch** [comment]
@roshanreji92 

![image](https://user-images.githubusercontent.com/21162161/104278320-0875b680-546e-11eb-873f-c8cb930df5f3.png)

**Comment by addisonlynch** [comment]
@roshanreji92 from the readme:

> **Please note that Google has closed this endpoint -- so the module may not work properly**

**Comment by hgarcia101685** [comment]
Yes.  Apologies for not following up with this sooner.  The endpoint will not work anymore.  Closing issue.
